spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:xxxx
#    username: xxxx
#    password: xxxx
#  jpa:
#    hibernate:
#      ddl-auto: 'update'
#    show-sql: 'true'
#    properties:
#      hibernate: org.hibernate.dialect.MySQL5Dialect
  config:
    import: optional:classpath:application-test.yml

logging:
  file:
    name: app_logs/app_log.log
    max-size: 10KB
    total-size-cap: 10MB
    max-history: 30
    clean-history-on-start: 'false'
  pattern:
    console: "%d {yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %logger{60} | %msg%n"
    file: "%d {yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %logger{60} | %msg%n"
    level:
      root: OFF
      com.hillel.task28springdata: INFO
      org.springframework.web: INFO
    rolling-file-name: app_logs/app_log-%d{yyyy-MM-dd}.%i.log