spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_25_sb
    username: 'root'
    password: '123456789'
  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: 'true'
  flyway:
    enabled: 'false'
    url: '${spring.datasource.url}'
    user: '${spring.datasource.username}'
    password: '${spring.datasource.password}'
    driver-class-name: '${spring.datasource.driver-class-name}'
    locations: 'db/migrations'
